image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: maven-build
  paths:
    - .m2/repository

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - export JAVA_TOOL_OPTIONS="-Djava.awt.headless=true"
    - mvn test
    - mvn verify
  artifacts:
    paths:
      - target/site/jacoco
    expire_in: 1 week
  coverage: '/Total.*?(\d+)%/'

# Documentation
#pages:
#  stage: deploy
#  script:
#    - mvn javadoc:javadoc
#    - cp -r target/site/apidocs/. public/
#  artifacts:
#    paths:
#      - public
#    expire_in: 1 day
#  only:
#    - master