image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  # Enable GitLab Advanced SAST (Ultimate feature)
  GITLAB_ADVANCED_SAST_ENABLED: true

# Cache and keep downloaded dependencies between CI pipelines
cache:
  key: maven-build
  paths:
    - .m2/repository

include:
  # NuGet Dependency Scanning
  # https://docs.gitlab.com/ee/user/application_security/dependency_scanning/
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  # Secret Detection
  # https://docs.gitlab.com/user/application_security/secret_detection/
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  # Static Application Security Testing (SAST)
  # https://docs.gitlab.com/user/application_security/sast/
  - template: Jobs/SAST.gitlab-ci.yml
  # Static analysis-based Code Quality evaluation for Java
  # https://szofttech.inf.elte.hu/components/code-quality-java
  - component: szofttech.inf.elte.hu/components/code-quality-java/maven@1

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    # JUnit test reports: auto-generated by the Maven Surefire Plugin
    # Code coverage reports: generated by the added JaCoCo Maven Plugin in JaCoco format and adding the "jacoco:report" parameter here
    #- mvn test jacoco:report
    # The jacoco.xml contains the overall coverage metric like this:
    # <report name="pacman">
    #  <counter type="LINE" missed="10" covered="90"/>
    # Let's process it with xmllint:
    #- apt-get update -yqq && apt-get install -yqq libxml2-utils
    #- |
     # COVERAGE=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" target/site/jacoco/jacoco.xml)
      #MISSED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" target/site/jacoco/jacoco.xml)
      #TOTAL=$((COVERAGE + MISSED))
      #PERCENT=$((100 * COVERAGE / TOTAL))
      #echo "TOTAL_COVERAGE=$PERCENT%"
    - mvn verify -Pcoverage
    - apt-get update -yqq && apt-get install -yqq libxml2-utils
    - |
      COVERAGE=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" target/site/jacoco/jacoco.xml)
      MISSED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" target/site/jacoco/jacoco.xml)
      TOTAL=$((COVERAGE + MISSED))
      PERCENT=$((100 * COVERAGE / TOTAL))
      echo "TOTAL_COVERAGE=$PERCENT%"
  artifacts:
    paths:
      - target/surefire-reports/
      - target/site/jacoco/
    reports:
      # Publish unit test results to GitLab UI
      # https://docs.gitlab.com/ci/testing/unit_test_reports/
      junit: target/surefire-reports/*.xml
      # Test coverage visualization on GitLab UI
      # https://docs.gitlab.com/ci/testing/code_coverage/
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco/jacoco.xml
  # Report code coverage for GitLab
  # https://docs.gitlab.com/ci/testing/code_coverage/
  coverage: '/TOTAL_COVERAGE=(\d+)%/'


# Documentation
pages:
  stage: deploy
  script:
    - mvn javadoc:javadoc
    - cp -r target/reports/apidocs/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master
    #- Dokumentáció

